package models.test.pronun;

public enum ErrorPattern {
    CONSONANT_ASSIMILATION,
    SYLLABLE_INITIAL_DELETION,
    FRONTING_1,
    FRONTING_2,
    FRONTING_3,
    BACKING,
    X_VELARISATION,
    STOPPING_1,
    STOPPING_2,
    STOPPING_3,
    AFFRICATION,
    DEASPIRATION,
    ASPIRATION,
    GLIDING,
    FINAL_N_DELETION,
    BACKING_N,
    FINAL_NG_DELETION,
    TRIPHTHONG_REDUCTION,
    DIPHTHONG_REDUCTION
}
