package models.test.pronun;

public enum ErrorPattern {
    CONSONANT_ASSIMILATION,
    SYLLABLE_INITIAL_DELETION,
    FRONTING,
    BACKING,
    X_VELARISATION,
    STOPPING,
    AFFRICATION,
    DEASPIRATION,
    ASPIRATION,
    GLIDING,
    FINAL_N_DELETION,
    BACKING_N,
    TRIPHTHONG_REDUCTION,
    DIPHTHONG_REDUCTION
}
